events {}

http {

    upstream blue {
        server blue:8080;
    }

    upstream green {
        server green:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://blue;
        }
    }
}
